- Dockerfile.template
#11 mentions a few extension that aren't available in the current image.
This PR builds and installs all additional modules when compiling PostgreSQL from source.
Also see: https://www.postgresql.org/docs/14/contrib.html (the instructions on how to build and install the modules are near the end of the page).
With the changes I can successfully build all images locally with `build-images.sh`. For the time being I only confirmed that the hstore extension works on the 13.3 image (`CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;`).
Please let me know if there is anything I can change or provide you with to get this merged.
> Build additional PostgreSQL modules

- 13.4/Dockerfile
- Dockerfile.template
- build-images.sh
This adds support for the uuid-ossp extension. Before rolling it out to all images (at 2-part respin process), just update the most recent image first so that users can test.
> Compile with libuuid - for PG v13.4 [release]

- 13.4/Dockerfile
- 9.6/Dockerfile
- Dockerfile.template
- build-images.sh
After PostgreSQL "common" extensions, then uuid-ossp, and then xml support, there's clearly a lot of extension support that was missing from this image. I went ahead and tracked down some Debian source packages and took a peak and what options they are enabling for their compiling of the PG packages. This is the result.
Like the PR from earlier today, this PR will re-spin PostgreSQL 13.4 to test with some customers. We're also respining 9.6.23 here for additional tests, especially for the issue in #17.
If the feedback from this is good, we will begin respinning the other images bringing the changes from this PR and #19 to all images.
> Align compile opts w/ Debian pkg [release]

- .circleci/config.yml
- push-images.sh
This is basically #27 but built with an updated `shared-tools`. There's now a `push-images.sh` script file to push each specific image and tag one by one. This prevents issues where sometimes a tag won't push even though it was built, as well as another issue you can find in the PR in shared-tools.
> Roll extension changes to all images (p3) [release]

- 10.20/Dockerfile
- 10.20/postgis/Dockerfile
- 11.15/Dockerfile
- 11.15/postgis/Dockerfile
- 13.6/Dockerfile
- 13.6/postgis/Dockerfile
- 14.2/Dockerfile
- 14.2/postgis/Dockerfile
- build-images.sh
- push-images.sh
Adding [latest release](https://www.postgresql.org/about/news/postgresql-142-136-1210-1115-and-1020-released-2402/) images, with the exception of 12.10 as that has already been added by https://github.com/CircleCI-Public/cimg-postgres/pull/43.
Created using:
```sh
./shared/gen-dockerfiles.sh 10.20 11.15 13.6 14.2
./build-images.sh
git add . # commit, push etc
```
> 10.20, 11.15, 13.6 and 14.2 images

- 10.22/Dockerfile
- 10.22/postgis/Dockerfile
- 11.17/Dockerfile
- 11.17/postgis/Dockerfile
- 12.12/Dockerfile
- 12.12/postgis/Dockerfile
- 13.8/Dockerfile
- 13.8/postgis/Dockerfile
- 14.5/Dockerfile
- 14.5/postgis/Dockerfile
- build-images.sh
- push-images.sh
postgres releases 10.22 11.17 12.12 13.8 14.5 for CVE-2022-2625 vulnerability.
> Pub: 10.22,11.17,12.12,13.8, and more. [release]

- docker-entrypoint.sh
Currently the PGDATA path is hardcoded for setting the `listen_addresses`, this fix allows using the custom PGDATA passed through.
Fixes: https://github.com/CircleCI-Public/cimg-postgres/issues/55
> fix setting of custom PGDATA

- variants/postgis.Dockerfile.template
Fixes #57
We will upgrade to v3.3.x or v3.4.x in the new year.
> Update PostGIS to v3.2.4

- .circleci/config.yml
- 12.13/Dockerfile
- Dockerfile.template
- custom-postgresql.conf
- pg_cron.sh
- adds code to install pg_cron extension
- allows user to modify the custom configuration
- moves all ENVs to top layers
- custom-postgressql.conf can be editable by all users who want to extend
- pg_cron.sh does not need to be limited to pg_cron
- additional features we are investigating are the additional of additional modules + enabling them
> feat: implement pg_cron capabilities

- variants/postgis.Dockerfile.template
Enables postgis out of the box, without needed to go into the database and enable the postgis extension. Closes #79
> feat: enables postgis out of the box in the template

- README.md
Fix instruction for building docker file locally.
Attempting to follow the existing instructions resulted in like these:
> ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::n121hzsjwlavfwipi9m4394vk: "/docker-entrypoint.sh": not found
This is because the file is in the root of the repo, so the command must be run from that location. 
> Minor fix to README for local testing

- Dockerfile.template
This adds PG Partman support to the base image. 
From https://github.com/pgpartman/pg_partman:
> pg_partman is an extension to create and manage both time-based and
> serial-based table partition sets. Native partitioning in PostgreSQL
> 10 is supported as of pg_partman v3.0.1 and much more extensively as
> of 4.0.0 along with PostgreSQL 11.
I opted to not install the background worker, since the base image already has pg_cron.
This appears to add about 20 MB to the base image size, when building as a separate layer:
```
$ docker image ls | grep cimg/post
cimg/postgres               12.9-partman          586ec1dac200   About an hour ago   2.1GB
cimg/postgres               12.9                  37dfce59e2e3   18 months ago       2.08GB
```
I would like to use Partman for local development …
> feat: add support for PG Partman

- Dockerfile.template
- README.md
---
Installs but disables pgtap extension by default
Removes enabling pgtap by default, which can break user builds, especially when they are using pgtap with historical changes. With this, all extensions and configurations should be created by the user for their needs.
If applicable, include a link to the related GitHub issue that this PR will close.
> remove pgtap being enabled by default

- Dockerfile.template
---
Purge build deps to shrink image from 2.42 GB to 1.76 GB
The space savings are for the 12.15 image, built locally with this commit compared with the latest published version.
Combine the pg and pg_cron layers to avoid installing & purging build-depends several times.
Gosu is used in entrypoint, so it is not purged.
locales is required by Pg at runtime, so it is not purged. 
```
~/src/cimg-postgres $ docker image ls | awk 'NR==1 || /12.15/'
REPOSITORY           TAG               IMAGE ID       CREATED         SIZE …
```
> Purge build deps to shrink the 12.15 image from 2.47 GB to 1.76 GB

- Dockerfile.template
- custom-postgresql.conf
---
This fixes ownership of the files in the /etc/postgresql directory, so the pg_cron.sh script can amend these files as it expects to do. 
Due to incorrect ownership of /etc/postgresql/custom-postgresql.conf the pg_cron.sh script was not able to add POSTGRES_DB to the `cron.database_name` config. Thus the only DB that would work with pg_cron is the 'circle_test' DB, as this was hard-coded in the example file.
This fixes ownership of the files in the /etc/postgresql directory, so the pg_cron.sh script can run without errors.
Please …
> Allow pg_cron to work on any configured POSTGRES_DB

- .circleci/config.yml
- Dockerfile.template
- manifest
- variants/postgis.Dockerfile.template
This PR adds multi architecture images with arm64 support
Enables arm64 support using the updating tooling in cimg-shared and cimg-orb
This also fixes build failures in the postgis variant and optimises building to utilise all the cpu available for faster builds
For now the testing portion is removed due to how buildx jobs work, but we will revisit this at a later date. I have manually verified these images run Postgres successfully
Test build for all in-support versions: https://app.circleci.com/pipelines/github/CircleCI-Public/cimg-postgres/421/workflows/f1e82e94-8556-4d9f-8946-a2d30f822c2c/jobs/404
> Add Arm64 support

- postgresFeed.sh
---
Pulls in an updated postgis version when a new postgres version has been detected
postgis was seldom being updated - the repository itself does not release that often. With postgres already having EOL'd versions 10 and 11, and with postgres 16 being released, the version of postGIS we were using is not compatible. This aims to ensure the postgis version is updated and supports the versions that postgres themselves do
- [no] I have made changes to the …
> feat: automate postgis versioning

- postgresFeed.sh
---
Set a condition to not update EOL versions and remove the releases.txt file that is generated for checking source downloads
This was adding a file to the generated releases that we do not want to keep, and we do not support EOL versions. A separate PR should be made to remove the major versions in the repository to clean it up
If applicable, include a link to the related GitHub issue that this PR will close.
- [N/A] I have made changes to the …
> refactor: remove releases.txt and set EOL version

- Dockerfile.template
Removes unnecessary `build-essential` package from build dependencies.
PostgreSQL requires `libllvm14` package for JIT compilation. 
The newly added `build-essential` in build dependencies causes `libllvm14` to be incorrectly purged during the cleanup phase.
As `build-essential` does not seem to be used during the build phase, we can remove it.
Fixes #129
> fix: remove build-essential to prevent llvm package purge

- pg_cron.sh
Updates `pg_cron.sh` to use the `PGDATA` environment variable instead of a hardcoded Postgres data directory path.
Fix for #113. 
> Update pg_cron.sh to use  instead of hard coded path
